
GET http://localhost:5858/users

####
GET http://localhost:5858/users/1

####
POST  http://localhost:5858/users
Content-Type: application/json

{
     "firstname": "Patrick",
    "lastname": "Calvaire",
    "entryage": 20,
    "gender": "male"
}

####
PATCH   http://localhost:5858/users/3
Content-Type: application/json

{
     "firstname": "Patrick",
    "lastname": "Brian",
    "entryage": 20,
    "gender": "male"
}

####
DELETE  http://localhost:5858/users/3